name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip
        run: |
          ls -la
          ZIP=$(ls *.zip 2>/dev/null | head -n1)
          unzip -o "$ZIP" -d tmp
          mv tmp/*/*. 2>/dev/null || mv tmp/*. 2>/dev/null || true
          rm -rf tmp "$ZIP"
          ls -la

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Web
        run: |
          npm install
          npm run build
          npx cap sync android

      - name: Fix Gradle
        run: |
          sed -i 's/gradle-.*-all.zip/gradle-8.13-all.zip/' android/gradle/wrapper/gradle-wrapper.properties
          chmod +x android/gradlew

      - name: Build APK AAB
        run: |
          cd android
         ./gradlew assembleDebug
         ./gradlew bundleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: android/app/build/outputs/apk/debug/*.apk

      - uses: actions/upload-artifact@v4
        with:
          name: AAB
          path: android/app/build/outputs/bundle/release/*.aab
